//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marija_Bozic_Dan_57.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllArticals", ReplyAction="http://tempuri.org/IService1/GetAllArticalsResponse")]
        Service.Models.Artical[] GetAllArticals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllArticals", ReplyAction="http://tempuri.org/IService1/GetAllArticalsResponse")]
        System.Threading.Tasks.Task<Service.Models.Artical[]> GetAllArticalsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateArtical", ReplyAction="http://tempuri.org/IService1/UpdateArticalResponse")]
        void UpdateArtical(Service.Models.Artical artical);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateArtical", ReplyAction="http://tempuri.org/IService1/UpdateArticalResponse")]
        System.Threading.Tasks.Task UpdateArticalAsync(Service.Models.Artical artical);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewArtical", ReplyAction="http://tempuri.org/IService1/AddNewArticalResponse")]
        void AddNewArtical(Service.Models.Artical artical);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewArtical", ReplyAction="http://tempuri.org/IService1/AddNewArticalResponse")]
        System.Threading.Tasks.Task AddNewArticalAsync(Service.Models.Artical artical);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetArticalByName", ReplyAction="http://tempuri.org/IService1/GetArticalByNameResponse")]
        Service.Models.Artical GetArticalByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetArticalByName", ReplyAction="http://tempuri.org/IService1/GetArticalByNameResponse")]
        System.Threading.Tasks.Task<Service.Models.Artical> GetArticalByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Marija_Bozic_Dan_57.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Marija_Bozic_Dan_57.ServiceReference1.IService1>, Marija_Bozic_Dan_57.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Service.Models.Artical[] GetAllArticals() {
            return base.Channel.GetAllArticals();
        }
        
        public System.Threading.Tasks.Task<Service.Models.Artical[]> GetAllArticalsAsync() {
            return base.Channel.GetAllArticalsAsync();
        }
        
        public void UpdateArtical(Service.Models.Artical artical) {
            base.Channel.UpdateArtical(artical);
        }
        
        public System.Threading.Tasks.Task UpdateArticalAsync(Service.Models.Artical artical) {
            return base.Channel.UpdateArticalAsync(artical);
        }
        
        public void AddNewArtical(Service.Models.Artical artical) {
            base.Channel.AddNewArtical(artical);
        }
        
        public System.Threading.Tasks.Task AddNewArticalAsync(Service.Models.Artical artical) {
            return base.Channel.AddNewArticalAsync(artical);
        }
        
        public Service.Models.Artical GetArticalByName(string name) {
            return base.Channel.GetArticalByName(name);
        }
        
        public System.Threading.Tasks.Task<Service.Models.Artical> GetArticalByNameAsync(string name) {
            return base.Channel.GetArticalByNameAsync(name);
        }
    }
}
